language: ruby

os: osx

rvm:
  - 2.6

before_install:
  - brew update
  - brew --version
  - gem install rubocop rubocop-performance rubocop-rspec
  - gem install activesupport -v 5.2.4.1
  - mkdir -p /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
  - cp -rf . /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
  - cd /usr/local/Homebrew/Library/Homebrew
  - gem install bundler:1.17.2

script:
  - cd /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
  - rubocop --version
  - rubocop
  - brew cu pin java
  - brew cu pinned
  - brew cu -y --no-brew-update
  - java --version > java.test.out && cat java.test.out | grep -q 13.
  - rm -f java.test.out
  - brew cu unpin java
  - brew cu -y --no-brew-update
  - java --version > test && cat test | grep -q 14.
